version: '3'

services:
  mysql:
    hostname: mysql
    image: mysql
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: lsf
    expose:
      - '3306'
    ports:
      - '3308:3306'
  
  incident_backend:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    environment:
      - APP_ENV=prod
    command: bash -c 'mysqld & python migrate.py'